version: '3'

services:
  server:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: /pech
  client1:
    build: client/
    command: /client server:8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  client2:
    build: client/
    command: /client server:8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  client3:
    build: client/
    command: /client server:8080
    stdin_open: true # docker run -i
    tty: true        # docker run -t
